### PR TITLE
README: mark as unmaintained

### PR DESCRIPTION
**Pull request by zimbatm**
~~The box is now offline.~~ EDIT: I think I misread a message

Once this PR is merged, I will mark the repo as archived.

### CODE REVIEW

**Comment by Mic92** [comment]
Interesting I can still access it.

**Comment by vcunat** [comment]
I've found it quite useful when fixing packaging issues that wouldn't reproduce on x86_64-linux.  Otherwise I personally don't have any replacement.

This PR links to https://nix-community.org/community-builder but that also links back to this community box, so that would better get fixed, too.  But I'm more sad that I'm not aware of any replacement (so far).

**Comment by zimbatm** [comment]
I asked Eelco for access to the Equinix Metal account to manage the machine appropriately.

**Comment by vcunat** [comment]
So the path would be instead to keep it, I hope, and make it owned by whole infra team? https://github.com/orgs/NixOS/teams/infra

**Pull request closed without merging**
