### PR TITLE
Add armv7l-linux to extra-platforms

### PR DESCRIPTION
**Pull request by expipiplus1**
CC @lheckemann

### CODE REVIEW

**Comment by lheckemann** [comment]
I don't think this is a good idea, since the results are so poor (and if we do do this we should probably also add armv6l-linux at least), preferring setting it on an ad-hoc basis using the command line or `~/.config/nix/nix.conf`.

**Comment by grahamc** [comment]
@lheckemann could you submit some docs on how to do that?

**Comment by lheckemann** [comment]
Where?

**Comment by grahamc** [comment]
README I guess :)

**Comment by lheckemann** [comment]
Oh hm. I just realised that this doesn't seem to work in any capacity with remote builds. I'd expect `ssh-ng://user@aarch64.nixos.community?extra-platforms=armv7l-linux` to work , but it doesn't (complains about an unknown option) :/ nor does having the setting in the per-user nix.conf affect remote builds. Not sure what to recommend here. I think both of these ways *should* work really, but don't understand why they don't.

**Pull request closed without merging**
