### PR TITLE
Grants @blogle access to the aarch64 community box

### PR DESCRIPTION
**Pull request by blogle**
- [x] I have read the entire README https://github.com/nix-community/aarch64-build-box
- [x] I completely understood the README https://github.com/nix-community/aarch64-build-box
- [x] I know when I can't trust the builder, as explained in the README

### CODE REVIEW

**Comment by blogle** [comment]
cc @lovesegfault :pray:

**Comment by lovesegfault** [comment]
I vouch for @blogle (cc. @grahamc)

**Comment by grahamc** [comment]
I understand this is for NixOS on the jetson work, sounds cool :).

**Comment by blogle** [comment]
thanks for the merge @grahamc, much appreciated

**Pull request merged**
